#!/bin/sh -

builtin . /etc/shrc;

_main() {
  local SYSTEM_DIR=$( sysdir );

  local MNT_DIR="${SYSTEM_DIR}/mnt";
  if ! is-mounted "$MNT_DIR"; then
    errmsg "$(bright-white ${MNT_DIR}) must be mounted before testing any filesystem(s)."; return 1;
  fi

  local RC=0;
  local THIS=$( /bin/realpath "$0" );
  local NAME=$( /usr/bin/basename "$THIS" );
  local HERE=$( /usr/bin/dirname "$THIS" );

  # Capture the current filesystem state to compare noschg flags with below. 
  # *NOTE* we run chdir here to use the same output format as the original (relative paths).
  local FILES_LIST="${HERE}/${NAME}.FILES";
  local FILES_LIST_CURR=$( /usr/bin/mktemp -t 'homewall.immutable-fs.FILES' );
  ( builtin chdir "$MNT_DIR" && /usr/bin/find . -flags noschg | /usr/bin/sort -dui ) >> "$FILES_LIST_CURR"

  ## ASSERTIONS-BEGIN ##

  # This should exit if it fails as its required for the rest of the assertions.
  assert "${FILES_LIST} exists." test -f "$FILES_LIST" || exit 1
  assert "The filesystem is system-immutable." /usr/bin/diff --brief "$FILES_LIST" "$FILES_LIST_CURR" || RC=1

  ## ASSERTIONS-END ##

  if [ -f "$FILES_LIST_CURR" ]; then
    /bin/rm -f "$FILES_LIST_CURR";
  fi

  exit "$RC";
}
_main;
