#!/bin/sh -

builtin . /etc/shrc;

_main() {
  local SYSTEM_DIR=$( sysdir );

  local FILES_DIR="${SYSTEM_DIR}/files";
  local RC_CONF="${FILES_DIR}/etc/rc.conf.local";
  local L1='ifconfig_ale0_name="ext0"';
  local L2='ifconfig_re0_name="int0"';
  local L3='ifconfig_ext0="DHCP group egress"';
  local L4='ifconfig_int0="inet 192.168.1.254/24 group ingress"';
  local RC=0;

  ## ASSERTIONS-BEGIN ##

  assert "${RC_CONF} exists" test -f "$RC_CONF" || RC=1
  assert "${RC_CONF} contains: ${L1}" is-line-included "$RC_CONF" "$L1" || RC=1
  assert "${RC_CONF} contains: ${L2}" is-line-included "$RC_CONF" "$L2" || RC=1
  assert "${RC_CONF} contains: ${L3}" is-line-included "$RC_CONF" "$L3" || RC=1
  assert "${RC_CONF} contains: ${L4}" is-line-included "$RC_CONF" "$L4" || RC=1

  ## ASSERTIONS-END ##

  return "$RC";
}
_main;

