#!/bin/sh -

builtin . /etc/shrc

_create_nics() {
  #create-jail-epair homewall ext0 group egress;
  #create-jail-epair homewall int0 inet 192.168.1.254/24 group ingress;

  # Uncomment to emulate hardware on test computer.
  create-jail-epair homewall ale0;
  create-jail-epair homewall re0;
}

_main() {
  # Only attempt to create the nics when we're alreayd within a jail env.
  # When we're on the host system, we only want to setup the jails filesystem
  # so it can be null-mounted into the bastille jail, dev0.
  local IS_JAIL=$( /sbin/sysctl -qien security.jail.jailed );
  if [ "$IS_JAIL" -eq 1 ]; then
    _create_nics || return 1
  fi
}
_main;
