#!/bin/sh -

builtin . /etc/shrc;

_main() {
    local SYSTEM_NAME=$( sysname );
    local SYSTEM_DIR=$( sysdir "$SYSTEM_NAME" );
    local DATA_DIR="${SYSTEM_DIR}/data";
    local FILES_DIR="${SYSTEM_DIR}/files";
    local MNT_DIR="${SYSTEM_DIR}/mnt";
    if ! is-mounted "$MNT_DIR"; then
        errmsg "$(bright-white ${MNT_DIR}) must be mounted before resetting passwords."; return 1;
    fi

    local RC=0;
    local FP='';
    local UN='';
    local UNS='root:ams';
    local IFS=':'; for UN in ${UNS}; do
        FP="${DATA_DIR}/pw.${UN}.SHA512";
        if [ ! -f "$FP" ]; then
            notfile "$FP"; return 1;
        fi  
        if is-empty-file "$FP"; then
            empty-file "$FP"; return 1;
        fi

        if ( /bin/cat "$FP" | /usr/sbin/pw -V ${FILES_DIR}/etc usermod -n ${UN} -H0 ) >>/dev/null 2>&1; then
            passmsg "Reset the password for $(orange ${UN})."; 
        else
            errmsg "Resetting the password for $(orange ${UN}) failed.";
            RC=1;
        fi
    done

    exit $RC; 
}
_main;
