#!/bin/sh -

builtin . /etc/shrc;

_main() {
  local SYSTEM_DIR=$( sysdir );

  local MNT_DIR="${SYSTEM_DIR}/mnt";
  if ! is-mounted "$MNT_DIR"; then
    errmsg "$(bright-white ${MNT_DIR}) must be mounted before testing any filesystem(s)."; return 1;
  fi

  local RC=0;

  local JAIL_DIR="${MNT_DIR}/jails/thin/nginx";
  assert "${JAIL_DIR} is a directory" test -d "$JAIL_DIR" || RC=1
  assert "${JAIL_DIR} has the owner: root:wheel" is-owner "$JAIL_DIR" root:wheel || RC=1
  assert "${JAIL_DIR} has the mode: u=rwx,go=rx" is-mode "$JAIL_DIR" u=rwx,go=rx || RC=1
  assert "${JAIL_DIR} has the flag: schg" is-flag "$JAIL_DIR" schg || RC=1

  local SCRIPTS_DIR="${JAIL_DIR}/scripts";

  local PREPARE="${SCRIPTS_DIR}/prepare";
  assert "${PREPARE} is a file" test -f "$PREPARE" || RC=1
  assert "${PREPARE} has the owner: root:wheel" is-owner "$PREPARE" root:wheel || RC=1
  assert "${PREPARE} has the mode: u=rwx,go=rx" is-mode "$PREPARE" u=rwx,go=rx || RC=1
  assert "${PREPARE} has the flag: schg" is-flag "$PREPARE" schg || RC=1

  local CREATED="${SCRIPTS_DIR}/created";
  assert "${CREATED} is a file" test -f "$CREATED" || RC=1
  assert "${CREATED} has the owner: root:wheel" is-owner "$CREATED" root:wheel || RC=1
  assert "${CREATED} has the mode: u=rwx,go=rx" is-mode "$CREATED" u=rwx,go=rx || RC=1
  assert "${CREATED} has the flag: schg" is-flag "$CREATED" schg || RC=1
  assert "${CREATED} invokes the functions: _main _create_nics" is-function-invoked "$CREATED" _main _create_nics || RC=1

  #local PRESTOP="${SCRIPTS_DIR}/prestop";
  #assert "${PRESTOP} is a file" test -f "$PRESTOP" || RC=1
  #assert "${PRESTOP} has the owner: root:wheel" is-owner "$PRESTOP" root:wheel || RC=1
  #assert "${PRESTOP} has the mode: u=rwx,go=rx" is-mode "$PRESTOP" u=rwx,go=rx || RC=1
  #assert "${PRESTOP} has the flag: schg" is-flag "$PRESTOP" schg || RC=1

  local RELEASE="${SCRIPTS_DIR}/release";
  assert "${RELEASE} is a file" test -f "$RELEASE" || RC=1
  assert "${RELEASE} has the owner: root:wheel" is-owner "$RELEASE" root:wheel || RC=1
  assert "${RELEASE} has the mode: u=rwx,go=rx" is-mode "$RELEASE" u=rwx,go=rx || RC=1
  assert "${RELEASE} has the flag: schg" is-flag "$RELEASE" schg || RC=1
  assert "${RELEASE} invokes the functions: _main _destroy_nics" is-function-invoked "$RELEASE" _main _destroy_nics || RC=1

  exit "$RC";
}
_main;
