#!/bin/sh -

builtin . /etc/shrc;

_main() {
  local SYSTEM_DIR=$( sysdir );

  local MNT_DIR="${SYSTEM_DIR}/mnt";
  if ! is-mounted "$MNT_DIR"; then
    errmsg "$(bright-white ${MNT_DIR}) must be mounted before testing any filesystem(s)."; return 1;
  fi

  local RC=0;
  local CRONTAB="${MNT_DIR}/etc/crontab";
  local ACCOUNT_DIR="${MNT_DIR}/var/account";
  local ACCT="${ACCOUNT_DIR}/acct";
  local ETC_PERIODIC_DIR="${MNT_DIR}/etc/periodic";
  local USR_LOCAL_ETC_PERIODIC_DIR="${MNT_DIR}/usr/local/etc/periodic";
  local BOOT_LOADER="${MNT_DIR}/boot/loader.conf";
  local BOOT_LOADER_LOCAL="${MNT_DIR}/boot/loader.conf.local";

  ## ASSERTIONS-BEGIN ##

  assert "${BOOT_LOADER} is a file" test -f "$BOOT_LOADER" || RC=1
  assert "${BOOT_LOADER} has the mode: u=rw,go=" is-mode "$BOOT_LOADER" u=rw,go= || RC=1
  assert "${BOOT_LOADER} has the owner: root:wheel" is-owner "$BOOT_LOADER" root:wheel || RC=1
  assert "${BOOT_LOADER} has the flag: schg" is-flag "$BOOT_LOADER" schg || RC=1

  assert "${BOOT_LOADER_LOCAL} is a symlink" test -L "$BOOT_LOADER_LOCAL" || RC=1
  assert "${BOOT_LOADER_LOCAL} has the mode: u=rwx,go=rx" is-mode "$BOOT_LOADER_LOCAL" u=rwx,go=rx || RC=1
  assert "${BOOT_LOADER_LOCAL} has the owner: root:wheel" is-owner "$BOOT_LOADER_LOCAL" root:wheel || RC=1
  assert "${BOOT_LOADER_LOCAL} has the flag: schg" is-flag "$BOOT_LOADER_LOCAL" schg || RC=1

  assert "${CRONTAB} is file" test -f "$CRONTAB" || RC=1
  assert "${CRONTAB} has the mode: u=rw,go=r" is-mode "$CRONTAB" u=rw,go=r || RC=1
  assert "${CRONTAB} has the owner: root:wheel" is-owner "$CRONTAB" root:wheel || RC=1
  assert "${CRONTAB} has the flag: schg" is-flag "$CRONTAB" schg || RC=1

  assert "${ETC_PERIODIC_DIR} does not exist" test ! -e "$ETC_PERIODIC_DIR" || RC=1

  assert "${USR_LOCAL_ETC_PERIODIC_DIR} does not exist" test ! -e "$USR_LOCAL_ETC_PERIODIC_DIR" || RC=1

  assert "${ACCOUNT_DIR} is a directory" test -d "$ACCOUNT_DIR" || RC=1
  assert "${ACCOUNT_DIR} has the mode: u=rwx,g=rx,o=" is-mode "$ACCOUNT_DIR" u=rwx,g=rx,o= || RC=1
  assert "${ACCOUNT_DIR} has the owner: root:wheel" is-owner "$ACCOUNT_DIR" root:wheel || RC=1
  assert "${ACCOUNT_DIR} lacks the flag: schg" is-flag "$ACCOUNT_DIR" noschg || RC=1

  assert "${ACCT} is a file" test -f "$ACCT" || RC=1
  assert "${ACCT} has the mode: u=rw,g=r,o=" is-mode "$ACCT" u=rw,g=r,o= || RC=1
  assert "${ACCT} has the owner: root:wheel" is-owner "$ACCT" root:wheel || RC=1
  assert "${ACCT} lacks the flag: schg" is-flag "$ACCT" noschg || RC=1

  ## ASSERTIONS-END ##

  exit "$RC";
}
_main;
