#!/bin/sh -
#
# Confirm that /etc/shrc et al. exists.
#

builtin . /etc/shrc;

_main() {
  local SYSTEM_DIR=$( sysdir  );

  local MNT_DIR="${SYSTEM_DIR}/mnt";
  if ! is-mounted "$MNT_DIR"; then
    errmsg "$(bright-white ${MNT_DIR}) must be mounted before testing any filesystem(s)."; return 1;
  fi

  local RC=0;
  local ETC_DIR="${MNT_DIR}/etc";

  local PROFILE="${ETC_DIR}/profile";
  assert "${PROFILE} is a file" test -f "$PROFILE" || RC=1
  assert "${PROFILE} has the owner: root:wheel" is-owner "$PROFILE" root:wheel || RC=1
  assert "${PROFILE} has the mode: u=rw,go=r" is-mode "$PROFILE" u=rw,go=r || RC=1 
  assert "${PROFILE} has the flag: schg" is-flag "$PROFILE" schg || RC=1

  local SHRC="${ETC_DIR}/shrc";
  assert "${SHRC} is a file" test -f "$SHRC" || RC=1
  assert "${SHRC} has the owner: root:wheel" is-owner "$SHRC" root:wheel || RC=1
  assert "${SHRC} has the mode: u=rw,go=r" is-mode "$SHRC" u=rw,go=r || RC=1
  assert "${SHRC} has the flag: schg" is-flag "$SHRC" schg || RC=1

  local SHRC_MD5="${ETC_DIR}/shrc.MD5";
  assert "${SHRC_MD5} is a file" test -f "$SHRC_MD5" || RC=1
  assert "${SHRC_MD5} has the owner: root:wheel" is-owner "$SHRC_MD5" root:wheel || RC=1
  assert "${SHRC_MD5} has the mode: u=rw,go=r" is-mode "$SHRC_MD5" u=rw,go=r || RC=1
  assert "${SHRC_MD5} has the flag: schg" is-flag "$SHRC_MD5" schg || RC=1

  local SHRC_DIR="${ETC_DIR}/shrc.d";
  assert "${SHRC_DIR} is a directory" test -d "$SHRC_DIR" || RC=1
  assert "${SHRC_DIR} has the owner: root:wheel" is-owner "$SHRC_DIR" root:wheel || RC=1
  assert "${SHRC_DIR} has the mode: u=rw,go=r" is-mode "$SHRC_DIR" u=rwx,go=rx || RC=1
  assert "${SHRC_DIR} has the flag: schg" is-flag "$SHRC_DIR" schg || RC=1

  exit "$RC";
}
_main;
